import { UserData } from '../models/UserData'

/**
 * 用户中心图表数据 - 模拟旧接口的chartData
 */
export const userChartDataSeed = [
  {
    id: 'user_chart_1',
    type: 'chart',
    title: 'userInfo.week.1',
    value: 1,
    list: [
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionA',
        len: 1,
        bid: 'A',
        pid: 'A',
      },
      {
        type: 'userInfo.type.optionC',
        status: 'userInfo.status.optionB',
        len: 5,
        bid: 'c',
        pid: 'B',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionC',
        len: 3,
        bid: 'A',
        pid: 'C',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionA',
        len: 1,
        bid: 'A',
        pid: 'A',
      },
      {
        type: 'userInfo.type.optionB',
        status: 'userInfo.status.optionA',
        len: 6,
        bid: 'B',
        pid: 'A',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionC',
        len: 1,
        bid: 'A',
        pid: 'C',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionA',
        len: 1,
        bid: 'A',
        pid: 'A',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionB',
        len: 1,
        bid: 'A',
        pid: 'B',
      },
      {
        type: 'userInfo.type.optionB',
        status: 'userInfo.status.optionA',
        len: 1,
        bid: 'B',
        pid: 'A',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionC',
        len: 1,
        bid: 'A',
        pid: 'C',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionD',
        len: 1,
        bid: 'A',
        pid: 'D',
      },
      {
        type: 'userInfo.type.optionC',
        status: 'userInfo.status.optionD',
        len: 1,
        bid: 'C',
        pid: 'D',
      },
      {
        type: 'userInfo.type.optionA',
        status: 'userInfo.status.optionD',
        len: 1,
        bid: 'A',
        pid: 'D',
      },
    ],
  },
  {
    id: 'user_chart_2',
    type: 'chart',
    title: 'userInfo.month.1',
    value: 0,
  },
  {
    id: 'user_chart_3',
    type: 'chart',
    title: 'userInfo.month.2',
    value: 0,
  },
  {
    id: 'user_chart_4',
    type: 'chart',
    title: 'userInfo.month.3',
    value: 0,
  },
  {
    id: 'user_chart_5',
    type: 'chart',
    title: 'userInfo.month.4',
    value: 0,
  },
  {
    id: 'user_chart_6',
    type: 'chart',
    title: 'userInfo.month.5',
    value: 0,
  },
  {
    id: 'user_chart_7',
    type: 'chart',
    title: 'userInfo.month.6',
    value: 0,
  },
  {
    id: 'user_chart_8',
    type: 'chart',
    title: 'userInfo.month.7',
    value: 0,
  },
  {
    id: 'user_chart_9',
    type: 'chart',
    title: 'userInfo.month.8',
    value: 0,
  },
  {
    id: 'user_chart_10',
    type: 'chart',
    title: 'userInfo.month.9',
    value: 0,
  },
  {
    id: 'user_chart_11',
    type: 'chart',
    title: 'userInfo.month.10',
    value: 0,
  },
  {
    id: 'user_chart_12',
    type: 'chart',
    title: 'userInfo.month.11',
    value: 0,
  },
  {
    id: 'user_chart_13',
    type: 'chart',
    title: 'userInfo.month.12',
    value: 0,
  },
  {
    id: 'user_chart_14',
    type: 'chart',
    title: 'userInfo.month.13',
    value: 0,
  },
  {
    id: 'user_chart_15',
    type: 'chart',
    title: 'userInfo.month.14',
    value: 0,
  },
  {
    id: 'user_chart_16',
    type: 'chart',
    title: 'userInfo.month.15',
    value: 0,
  },
  {
    id: 'user_chart_17',
    type: 'chart',
    title: 'userInfo.month.16',
    value: 0,
  },
  {
    id: 'user_chart_18',
    type: 'chart',
    title: 'userInfo.month.17',
    value: 0,
  },
] as const

/**
 * 用户中心表格数据 - 模拟旧接口的tableData
 */
export const userTableDataSeed = [
  {
    id: 'user_table_1',
    type: 'table',
    bid: 'A',
    pid: 'D',
    name: 'GFD Company',
    time: '2021-12-18',
    businessType: 'userInfo.type.optionA',
    status: 'userInfo.status.optionD',
  },
  {
    id: 'user_table_2',
    type: 'table',
    bid: 'B',
    pid: 'A',
    name: 'WWWW Company',
    time: '2021-11-18',
    businessType: 'userInfo.type.optionB',
    status: 'userInfo.status.optionA',
  },
  {
    id: 'user_table_3',
    type: 'table',
    bid: 'C',
    pid: 'B',
    name: 'TGBYX Company',
    time: '2021-10-18',
    businessType: 'userInfo.type.optionC',
    status: 'userInfo.status.optionB',
  },
  {
    id: 'user_table_4',
    type: 'table',
    bid: 'B',
    pid: 'D',
    name: 'GF Company',
    time: '2021-09-18',
    businessType: 'userInfo.type.optionB',
    status: 'userInfo.status.optionC',
  },
  {
    id: 'user_table_5',
    type: 'table',
    bid: 'C',
    pid: 'C',
    name: 'Property management company',
    time: '2021-07-18',
    businessType: 'userInfo.type.optionA',
    status: 'userInfo.status.optionD',
  },
  {
    id: 'user_table_6',
    type: 'table',
    bid: 'A',
    pid: 'C',
    name: 'Property management company',
    time: '2020-12-23',
    businessType: 'userInfo.type.optionA',
    status: 'userInfo.status.optionC',
  },
  {
    id: 'user_table_7',
    type: 'table',
    bid: 'B',
    pid: 'C',
    name: 'GF Company',
    time: '2020-11-08',
    businessType: 'userInfo.type.optionB',
    status: 'userInfo.status.optionC',
  },
  {
    id: 'user_table_8',
    type: 'table',
    bid: 'B',
    pid: 'C',
    name: 'WWWW Company',
    time: '2020-10-18',
    businessType: 'userInfo.type.optionB',
    status: 'userInfo.status.optionC',
  },
  {
    id: 'user_table_9',
    type: 'table',
    bid: 'C',
    pid: 'D',
    name: 'WWWW Company',
    time: '2020-10-11',
    businessType: 'userInfo.type.optionC',
    status: 'userInfo.status.optionD',
  },
  {
    id: 'user_table_10',
    type: 'table',
    bid: 'C',
    pid: 'D',
    name: 'TGBYX Company',
    time: '2020-06-18',
    businessType: 'userInfo.type.optionC',
    status: 'userInfo.status.optionD',
  },
] as const
